export const fieldTypes = [
    'text',
    'textarea',
    'selector',
    'group',
    'checkbox',
    'radio',
    'title',
    'subtitle',
    'description',
    'list',
    'complex',
    'datetime',
    'columnContainer',
    'rowContainer',
];
